export type Locale = 'en' | 'mk'

export const useLanguage = () => {
  const locale = useState<Locale>('site-locale', () => 'en')

  const translations = {
    en: {
      navAbout: 'About Me',
      navServices: 'Services',
      navProjects: 'Selected Work',
      navContact: 'Contact',
      languageLabel: 'MK',
      heroTag: 'Editor / Visual Storyteller',
      heroTitle: 'I turn footage into stories.',
      heroWords: ['ADVERTISING', 'MUSIC VIDEOS', 'DOCUMENTARIES', 'SOCIAL MEDIA', 'COLOR GRADING'],
      aboutTitle: 'ABOUT ME',
      aboutP1:
        'I’m a Video Editor focused on creating engaging, polished, and story-driven content for commercials, music videos, documentaries, and digital media.',
      aboutP2:
        'My primary expertise is post-production using Adobe Premiere Pro, After Effects, and DaVinci Resolve, covering everything from assembly and color grading to motion graphics and visual effects.',
      aboutP3:
        'Before dedicating myself fully to video editing, I built a foundation in web development, working with modern web technologies to build responsive sites. This background gives me a distinct technical edge—allowing me to combine creative visual storytelling with a deep understanding of digital media formats, web integration, and technical asset management.',
      aboutP4:
        'Today, my focus is entirely on visual storytelling: turning raw footage into compelling videos that evoke emotion, communicate ideas clearly, and hold audience attention. I am always looking to collaborate with businesses, agencies, artists, and creative teams on ambitious video projects.',
      servicesTitle: 'Video editing packages',
      servicesLabel: 'Services',
      choosePackage: 'Choose package',
      popular: 'Popular',
      shortFormPrice: 'From $35',
      shortFormFeature1: 'Dynamic cuts & transitions',
      shortFormFeature2: 'Subtitles & sound design',
      shortFormFeature3: 'Color correction & grading',
      shortFormFeature4: 'Social-ready vertical exports',
      youtubePrice: 'From $100',
      youtubeFeature1: 'Audio cleanup & balancing',
      youtubeFeature2: 'Motion graphics & lower thirds',
      youtubeFeature3: 'Cinematic color grading',
      youtubeFeature4: 'B-roll integration & pacing',
      customPrice: 'Custom',
      customFeature1: 'Music videos & creative spots',
      customFeature2: 'Rhythm & narrative pacing',
      customFeature3: 'Advanced motion design & VFX pass',
      customFeature4: 'Cinematic color grading & audio sync',
      myMaterialsPrice: 'From $120',
      myMaterialsFeature1: 'Created using my stock footage, overlays & visual assets',
      myMaterialsFeature2: 'Music videos, promo ads & short documentary edits',
      myMaterialsFeature3: 'Custom motion graphics, text & sound design',
      myMaterialsFeature4: 'Full audio mixing & cinematic color grading',
      myMaterialsFeature5: 'Ready-to-publish high-resolution export',
      projectViewAll: 'View all',
      projectHint: 'Click for More ✦',
      projectFilm: 'Project film',
      contactTitle: 'Let’s build something worth watching.',
      contactName: 'Name',
      contactNamePlaceholder: 'Your name',
      contactEmail: 'Your Email',
      contactEmailPlaceholder: 'Your Email',
      contactPackage: 'Choose a package',
      contactSelectDefault: 'Select a service',
      contactProject: 'Project',
      contactProjectPlaceholder: 'Tell me about your idea',
      contactSend: 'Send inquiry',
      contactSending: 'Sending...',
      contactAvailable: 'Available for calls',
      footerText: 'Let’s talk about your next video project.',
      shortForm: 'Short-Form',
      shortFormDesc: 'Fast, punchy edits built for Reels, Shorts, and social-first content.',
      youtube: 'YouTube & Corporate',
      youtubeDesc: 'Brand videos, interviews, and polished long-form edits for digital channels.',
      custom: 'Custom Production',
      customDesc: 'Tailored storytelling for music videos, premium branded work, and documentary edits.',
      myMaterials: 'My Materials Production',
      myMaterialsDesc: 'Music videos, advertisements, and short documentaries built entirely from my materials and stock assets.',
      formPackageSubject: 'I’m interested in the',
      selectOptionShort: 'Short-Form',
      selectOptionYoutube: 'YouTube & Corporate',
      selectOptionCustom: 'Documentary & Custom',
      selectOptionMyMaterials: 'My Materials Production',
      aboutPageTitle: 'About Me',
      aboutPageP1: 'I’m a Video Editor focused on creating engaging, polished and story-driven content for advertising, music, documentaries and digital media.',
      aboutPageP2: 'My main focus is video editing, with experience in DaVinci Resolve, Adobe Premiere Pro and After Effects, including editing, color grading, motion graphics and visual effects.',
      aboutPageP3: 'Before focusing on video editing, I also gained experience in web development, working with modern web technologies and building websites. This background gave me a strong understanding of digital media and helped me develop a technical and creative approach to my work.',
      aboutPageP4: 'Today, my primary focus is video editing and visual storytelling. I enjoy turning raw footage into videos that communicate an idea, create emotion and keep the viewer engaged.',
      aboutPageP5: 'I’m continuously developing my skills and looking for opportunities to work with businesses, agencies, artists and creative teams on professional video projects.'
    },
    mk: {
      navAbout: 'За мене',
      navServices: 'Услуги',
      navProjects: 'Избрани дела',
      navContact: 'Контакт',
      languageLabel: 'EN',
      heroTag: 'Едитор / Визуелен раскажувач',
      heroTitle: 'Го претворам видеото во приказна.',
      heroWords: ['РЕКЛАМА', 'МУЗИЧКИ ВИДЕА', 'ДОКУМЕНТАРЦИ', 'СОЦИЈАЛНИ МЕДИУМИ', 'КОЛОР ГРАДИРАЊЕ'],
      aboutTitle: 'ЗА МЕНЕ',
      aboutP1:
        'Сум видео едитор фокусиран на креирање ангажирачки, полирани и приказно-водени содржини за реклами, музички видеа, документарци и дигитални медиуми.',
      aboutP2:
        'Мојот главен фокус е пост-продукција со користење на Adobe Premiere Pro, After Effects и DaVinci Resolve, вклучувајќи монтаж, колор градирање, motion graphics и визуелни ефекти.',
      aboutP3:
        'Пред целосно да се посветам на видео монтажата, изградив основа во веб развојот, работејќи со модерни веб технологии за креирање одговорни веб страници. Ова ми дава посебен технички предност — овозможувајќи да ги комбинирам креативното визуелно раскажување и длабокото разбирање на дигиталните медиумски формати, веб интеграцијата и управувањето со технички ресурси.',
      aboutP4:
        'Денес, мојот фокус е целосно визуелно раскажување: претворање на суровото видео во убедливи видеа кои предизвикуваат емоции, јасно ја пренесуваат идејата и ја задржуваат внимателноста на гледачот. Секогаш барам да соработувам со бизниси, агенции, уметници и креативни тимови на амбициозни видео проекти.',
      servicesTitle: 'Пакети за видео монтажа',
      servicesLabel: 'Услуги',
      choosePackage: 'Избери пакет',
      popular: 'Популарно',
      shortFormPrice: 'Од $35',
      shortFormFeature1: 'Динамични резови и транзиции',
      shortFormFeature2: 'Преводи и дизајн на звук',
      shortFormFeature3: 'Корекција и градирање на бои',
      shortFormFeature4: 'Вертикални експорти подготвени за социјални мрежи',
      youtubePrice: 'Од $100',
      youtubeFeature1: 'Чистење и балансирање на звукот',
      youtubeFeature2: 'Motion graphics и lower thirds',
      youtubeFeature3: 'Кинематографско градирање на бои',
      youtubeFeature4: 'Интеграција на B-roll и ритам на монтажата',
      customPrice: 'Кустом',
      customFeature1: 'Музички видеа и креативни спотови',
      customFeature2: 'Ритам и наративен тек',
      customFeature3: 'Напреден motion design и VFX обработка',
      customFeature4: 'Кинематографско градирање на бои и синхронизација на звук',
      myMaterialsPrice: 'Од $120',
      myMaterialsFeature1: 'Креирано со мои stock снимки, overlays и визуелни материјали',
      myMaterialsFeature2: 'Музички видеа, промо реклами и кратки документарни монтажи',
      myMaterialsFeature3: 'Прилагодени motion graphics, текст и sound design',
      myMaterialsFeature4: 'Целосен аудио микс и кинематографско градирање на бои',
      myMaterialsFeature5: 'Експорт со висока резолуција подготвен за објавување',
      projectViewAll: 'Погледни сите',
      projectHint: 'Кликни за повеќе ✦',
      projectFilm: 'Проектен филм',
      contactTitle: 'А да создадеме нешто вредно за гледање.',
      contactName: 'Име',
      contactNamePlaceholder: 'Вашето име',
      contactEmail: 'Вашиот емаил',
      contactEmailPlaceholder: 'Вашиот емаил',
      contactPackage: 'Избери пакет',
      contactSelectDefault: 'Избери услуга',
      contactProject: 'Проект',
      contactProjectPlaceholder: 'Кажи ми за твојата идеја',
      contactSend: 'Испрати барање',
      contactSending: 'Испраќање...',
      contactAvailable: 'Достапен за повици',
      footerText: 'Ајде да разговараме за твојот следен видео проект.',
      shortForm: 'Краток формат',
      shortFormDesc: 'Брзи, динамични монтажи создадени за Reels, Shorts и содржина за социјални медиуми.',
      youtube: 'YouTube & Корпоративно',
      youtubeDesc: 'Видео реклами, интервјуа и полирани монтажи за дигитални канали.',
      custom: 'Кустом продукција',
      customDesc: 'Прилагодено раскажување за музички видеа, премиум брендови и документарни монтажи.',
      myMaterials: 'Продукција со мои материјали',
      myMaterialsDesc: 'Музички видеа, реклами и кратки документарци создадени целосно од мои материјали и stock assets.',
      formPackageSubject: 'Сум заинтересиран за',
      selectOptionShort: 'Краток формат',
      selectOptionYoutube: 'YouTube & Корпоративно',
      selectOptionCustom: 'Документарни & Кустом',
      selectOptionMyMaterials: 'Продукција со мои материјали',
      aboutPageTitle: 'За мене',
      aboutPageP1: 'Сум видео едитор фокусиран на креирање ангажирачки, полирани и приказно-водени содржини за реклами, музика, документарци и дигитални медиуми.',
      aboutPageP2: 'Мојот главен фокус е видео монтажата, со искуство во DaVinci Resolve, Adobe Premiere Pro и After Effects, вклучувајќи монтаж, колор градирање, motion graphics и визуелни ефекти.',
      aboutPageP3: 'Пред да се посветам целосно на видео монтажата, стекнав искуство и во веб развојот, работејќи со модерни веб технологии и креирајќи веб страници. Ова ми помогна да развијам технички и креативен пристап кон мојата работа.',
      aboutPageP4: 'Денес, мојот главен фокус е видео монтажата и визуелното раскажување. Го сакаме да ги претворам суровите снимки во видеа кои ја пренесуваат идејата, создаваат емоции и го задржуваат вниманието на гледачот.',
      aboutPageP5: 'Континуирано ги развивам моите вештини и барам можности да работам со бизниси, агенции, уметници и креативни тимови на професионални видео проекти.'
    }
  } as const

  type TranslationKey = keyof typeof translations.en

  const t = (key: TranslationKey) => (translations[locale.value][key] ?? translations.en[key]) as any

  const toggleLanguage = () => {
    locale.value = locale.value === 'en' ? 'mk' : 'en'
  }

  return {
    locale,
    t,
    toggleLanguage
  }
}
